
name: Figma variables > tokens + styles

on:
  workflow_dispatch:
    inputs:
      file_key:
        description: 'The file key of the Figma file to be updated'
        required: true

jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: Set NPM version
        run: npm install -g npm@9.5.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Style Dictionary
        run: npm install -g style-dictionary

      - name: Clear tokens directory for demo
        run: bash cleanup.sh

      - name: Sync variables in Figma file to tokens
        run: npm run sync-figma-to-tokens -- --output tokens
        env:
          FILE_KEY: ${{ github.event.inputs.file_key }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_ACTION_VARIABLES_SYNC_FIGMA_TOKEN }}

      - name: Remove dollar signs from output (SD won't work otherwise)
        run: bash removedollarsigns.sh

      - name: Preprocess tokens to avoid naming conflicts
        run: npm run preprocess

      - name: Build Style Dictionary (uses config.json to define src/dest)
        run: npm run build
      - name: Ensure changes are added
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add tokens-prepared/ build/css/variables.css || true
          
      - name: Force Git add
        run: |
          git add tokens-prepared/
          git add build/css/variables.css

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '🔁 Update tokens from Figma'
          title: '🔁 Update tokens from Figma'
          body: 'Tokens updated from Figma file: https://www.figma.com/file/${{ github.event.inputs.file_key }}'
          branch: update/tokens-${{ github.run_id }}
          add-paths: |
            tokens-prepared/**
            build/css/variables.css
